# --------------------
# Define arguments.
# --------------------

# ==================== Alas ====================

Scheduler:
  Enable:
    type: checkbox
    value: false
    option: [ true, false ]
  NextRun: 2020-01-01 00:00:00
  Command: Alas
  ServerUpdate:
    value: 04:00
    display: hide
Emulator:
  Serial:
    value: auto
    valuetype: str
  PackageName:
    value: auto
    option: [ auto, ]
  GameLanguage:
    value: auto
    option: [ auto, jp, en ]
  ScreenshotMethod:
    value: auto
    option: [ auto, ADB, ADB_nc, uiautomator2, aScreenCap, aScreenCap_nc, DroidCast, DroidCast_raw, scrcpy ]
  ControlMethod:
    value: MaaTouch
    option: [ minitouch, MaaTouch ]
  AdbRestart: false
EmulatorInfo:
  Emulator:
    value: auto
    option: [
      auto,
      NoxPlayer,
      NoxPlayer64,
      BlueStacks4,
      BlueStacks5,
      BlueStacks4HyperV,
      BlueStacks5HyperV,
      LDPlayer3,
      LDPlayer4,
      LDPlayer9,
      MuMuPlayer,
      MuMuPlayerX,
      MuMuPlayer12,
      MEmuPlayer,
    ]
  name:
    value: null
    type: textarea
  path:
    value: null
    type: textarea
Error:
  Restart:
    value: game
    option: [ game, game_emulator ]
  SaveError: true
  ScreenshotLength: 1
  OnePushConfig:
    type: textarea
    mode: yaml
    value: 'provider: null'
Optimization:
  ScreenshotInterval: 0.3
  CombatScreenshotInterval: 1.0
  WhenTaskQueueEmpty:
    value: goto_main
    option: [ stay_there, goto_main, close_game, exit_aas, exit_aas_emulator, shutdown ]

# ==================== Daily ====================

Cafe:
  Reward: true
  Touch: true
  AutoAdjust: true
  SecondCafe: true
Invitation:
  Enable: true
  WaitingHour:
    value: 0
    option: [ 0, 3, 6, 9 ]
  Choice:
    value: list_top
    option: [ list_top, by_name ]
  Name:
    value: null
    type: textarea
  Substitute: false

Schedule:
  OnError:
    value: skip
    option: [ stop, skip ]

Choice1:
  Location:
    value: None
    option: [ None, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
  Classrooms:
    value: null
    type: textarea
Choice2:
  Location:
    value: None
    option: [ None, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
  Classrooms:
    value: null
    type: textarea
Choice3:
  Location:
    value: None
    option: [ None, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
  Classrooms:
    value: null
    type: textarea
Choice4:
  Location:
    value: None
    option: [ None, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
  Classrooms:
    value: null
    type: textarea
Choice5:
  Location:
    value: None
    option: [ None, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
  Classrooms:
    value: null
    type: textarea

Bounty:
  OnError:
    value: skip
    option: [ stop, skip ]

Highway:
  Stage:
    value: 0
    option: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
  Count: 2
DesertRailroad:
  Stage:
    value: 0
    option: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
  Count: 2
Schoolhouse:
  Stage:
    value: 0
    option: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
  Count: 2

Scrimmage:
  OnError:
    value: skip
    option: [ stop, skip ]

Trinity:
  Stage:
    value: 0
    option: [ 0, 1, 2, 3, 4 ]
  Count: 2
Gehenna:
  Stage:
    value: 0
    option: [ 0, 1, 2, 3, 4 ]
  Count: 2
Millennium:
  Stage:
    value: 0
    option: [ 0, 1, 2, 3, 4 ]
  Count: 2

TacticalChallenge:
  PlayerSelect:
    value: 0
    option: [ 0, 1, 2, 3 ]

NormalShop:
  Enable: false
  Purchases:
    value: 1
    option: [ 1, 2, 3, 4 ]
  "1": false
  "2": false
  "3": false
  "4": false
  "5": false
  "6": false
  "7": false
  "8": false
  "9": false
  "10": false
  "11": false
  "12": false
  "13": false
  "14": false
  "15": false
  "16": false
  "17": false
  "18": false
  "19": false
  "20": false

TacticalChallengeShop:
  Enable: false
  Purchases:
    value: 1
    option: [ 1, 2, 3, 4 ]
  "1": false
  "2": false
  "3": false
  "4": false
  "5": false
  "6": false
  "7": false
  "8": false
  "9": false
  "10": false
  "11": false
  "12": false
  "13": false
  "14": false
  "15": false

ItemStorage:
  AP:
    stored: StoredAP
    order: 1
    color: "#62ea6e"
  Credit:
    stored: StoredInt
    order: 2
    color: "#fdec00"
  Pyroxene:
    stored: StoredInt
    order: 3
    color: "#21befc"
  BountyTicket:
    stored: StoredBountyTicket
    order: 4
    color: "#94cb44"
  ScrimmageTicket:
    stored: StoredScrimmageTicket
    order: 5
    color: "#f86c6a"
  TacticalChallengeTicket:
    stored: StoredTacticalChallengeTicket
    order: 6
    color: "#7ac8e5"
